### ISSUE TITLE
Facing a error when I try to use this code

### ISSUE THREAD

**Issue by MiAutomations** [SmartHome-yourself/m5-dial-for-esphome#11]
Hello 

Thank you for this code !

I'm facing a issue when I try to use this code on the ESP Dashboard for the M5 Dial device:  

INFO ESPHome 2024.3.0
INFO Reading configuration /config/esphome/m5stack-rotatory-knob.yaml...
ERROR Error while reading config: Invalid YAML syntax:

´´´
Duplicate key "min_kelvin"
  in "/config/esphome/m5stack-rotatory-knob.yaml", line 36, column 13
NOTE: Previous declaration here:
  in "/config/esphome/m5stack-rotatory-knob.yaml", line 35, column 13 
´´´
  Can you please help me in order to solve this ? 
  
  Thank you

**Comment by danielscheidler** [comment]
yes, I've an error in the example code. you have to use min_kelvin for minimum and max_kelvin for maximum value in brightness_mode. 
I'll fix the readme later
