### ISSUE TITLE
Example configuration problems

### ISSUE THREAD

**Issue by jereskuta** [SmartHome-yourself/m5-dial-for-esphome#13]
Wrong naming in the example config. Replacing the names with the suggestions worked.

```
  [screenOffTime] is an invalid option for [shys_m5_dial]. Did you mean [screen_off_time]?
  screenOffTime: 45000
  
  [rotaryStepWidth] is an invalid option for [shys_m5_dial]. Did you mean [rotary_step_width]?
  rotaryStepWidth: 5
  
  [longPressDuration] is an invalid option for [shys_m5_dial]. Did you mean [long_press_duration]?
  longPressDuration: 1200
```

After fixing those, I can install the software successfully, however the Dial screen stays black and it is not working.

**Comment by jereskuta** [comment]
I got the software working. I  didn't properly configure the dial in home assistant.

**Comment by danielscheidler** [comment]
thx for your feedback. 
I fixed the parameters in the readme.

**Comment by HomeJJAssistan** [comment]
Thanks @jereskuta  I had the same Problem with the names, now is fixed.
