### ISSUE TITLE
Nordic fonts

### ISSUE THREAD

**Issue by Roysen66** [SmartHome-yourself/m5-dial-for-esphome#18]
Are there possible to add support for Nordic fonts? Something like this:
  - file: 'your_font.ttf'
    glyphs:
      ['&', '@', '!', ',', '.', '?', '"', '%', '(', ')', '+', '-', '_', ':', '°', '0',
       '1', '2', '3', '4', '5', '6', '7', '8', '9', 'A', 'B', 'C', 'D', 'E',
       'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S',
       'T', 'U', 'V', 'W', 'X', 'Y', 'Z', ' ', 'a', 'b', 'c', 'd', 'e', 'f',
       'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't',
       'u', 'v', 'w', 'x', 'y', 'z','å', 'Å', 'ä', 'Ø', 'ø', 'Ü', 'ü', '/']

**Comment by danielscheidler** [comment]
I think I've found a way to support special Chars with integrate a font as binary. First tests works with öäü and so on, but it looks like it's cutting the bottom pixels. I'll keep working on it

**Comment by Roysen66** [comment]
Thank you so much for your effort.

**Comment by danielscheidler** [comment]
fonts with special chars should work now in dev branch.
