### ISSUE TITLE
Where can i find the options flow?

### ISSUE THREAD

**Issue by PaulMofers** [SmartHome-yourself/m5-dial-for-esphome#19]
... rejected; If you trust this device and want to allow access for it to make Home Assistant service calls, you can enable this functionality in the options flow

**Comment by danielscheidler** [comment]
Settings - devices - esphome - your device

See Video at 9:30
https://youtu.be/4dE7YONEYVk?si=4O_IINUEqZ_h5A0G

PaulMofers ***@***.***> schrieb am Sa., 20. Apr. 2024, 16:44:
