### ISSUE TITLE
corotine taking to long after swipe action in "farbwahl modus"

### ISSUE THREAD

**Issue by PaulMofers** [SmartHome-yourself/m5-dial-for-esphome#23]
![image](https://github.com/SmartHome-yourself/m5-dial-for-esphome/assets/74146429/bc63237b-7618-4ab7-b45e-70927e6ddd4a)

this keeps coming back

**Comment by PaulMofers** [comment]
BTW, that discord link takes me to noting?

**Comment by danielscheidler** [comment]
it's only because display painting is taking more time. 
https://github.com/esphome/issues/issues/4717
