### ISSUE TITLE
Multiple light modes; how does it work?

### ISSUE THREAD

**Issue by fusionstream** [SmartHome-yourself/m5-dial-for-esphome#26]
In the example configuration, it is possible to enable dimm_mode, rgb_mode, white_mode all at the same time. 

How does one change between modes from the dial itself? Is it possible?

**Comment by fusionstream** [comment]
Awesome. Thank you!

For anyone coming across this, the swipe must occur from either edge of the screen. If it's too close to the middle, it'll just adjust the relevant setting

**Comment by danielscheidler** [comment]
Incidentally, this applies to both swipes. Both vertically and horizontally. It also goes out of the middle, but the swipe must make up at least 30% of the screen width. Otherwise it will not be considered a swipe, otherwise touch was often recognized as a swipe
