### ISSUE TITLE
AC Temperature still goes below minimum

### ISSUE THREAD

**Issue by fusionstream** [SmartHome-yourself/m5-dial-for-esphome#30]
It is possible to go below the minimum set temperature by rotating continuously

**Comment by danielscheidler** [comment]
Below the Minimum Set in the dial config or the Minimum of the climate? Actually, when reducing or increasing before setting, it is always checked against the min or max value that was set for the mode. But I'll Take a Look later

**Comment by fusionstream** [comment]
Yes sir. :)

    
      devices:
        climates:
          - entity: climate.thermostat
            name: A/C
            modes:
              temp_mode:
                rotary_step_width: 1
                min_temperature: 18
                max_temperature: 30

This goes down to 0

**Comment by danielscheidler** [comment]
Ok, I look at it. Today, however, is an exceptional holiday. ;)

**Comment by fusionstream** [comment]
All good mate. Take your time. Happy Labour Day! :)
