### ISSUE TITLE
After the last ESP update to version 2024.6.1 Stop Working

### ISSUE THREAD

**Issue by MiAutomations** [SmartHome-yourself/m5-dial-for-esphome#39]
Hello 

After the last ESP update to version 2024.6.1 my M5 Dial Stop Working

I changed the YAML code as needed 

ota:
  - platform: esphome
    password: "My Password"
    
But the device Still Offline And not connected ... 

Can some one please help me in order to try solve this issue? Thank you in advance

**Comment by fft1010** [comment]
Hi,
Same here. Daniel is already working on a solution.
all the best
Juergen

**Comment by danielscheidler** [comment]
should be fixed with commit c990ae7e468f35da9076eb070460a35741916fd8
Button handling has changed in the M5 Librarys. I force to use the older one as quick fix. 
I'll take a look at the changes to use the current versions later.

**Comment by SvenDowideit** [comment]
Thank you very much! My m5dial arrived 2 days ago, so your quick fix has allowed me to get something working :)
